### ISSUE TITLE
RFC-0005: Webpage translation plugin or extension needed(MM24)

### ISSUE THREAD

**Issue by Karma-Tsering** [OpenPecha/monlamai-feedbucket#162]
### Description
We require a browser extension that can translate an entire website into Tibetan.

### Completion Criteria
Upon loading the extension on a webpage, it should be capable of translating the entire content of the site into Tibetan.

1. Need auto pop up on new page
2. language selection
3. Toggle translated and original
4. Loading sign for each text
5. Shortcut key
6. Translate selected text
7. Theme according to browser's theme

### Implementation Plan
First prepare a mock and then update the gayshe la's code to match with mock.

![Image](https://github.com/user-attachments/assets/8641fa8f-e9ba-4f38-a9cd-60dc42690332)

![Image](https://github.com/user-attachments/assets/644c521b-e162-479f-867f-7eab1a914909)

### Sub Task

- [x] prepare a mock.
- [x] implement UI on html template
- [x] setup JS file for environment variable / test import method
- [x] improve caching with local storage
- [x] implementing loading state
- [x] selecting text on website to tranlate

**Comment by tenkus47** [comment]
![Image](https://github.com/user-attachments/assets/773ba930-2bea-49ae-bc08-12726e1cb590)

under review
