### ISSUE TITLE
RFC0032: Figma mock for padma

### ISSUE THREAD

**Issue by tenkus47** [OpenPecha/monlamai-feedbucket#163]
### Description
Designing a mock for the Upcoming project (Padma Chatbot). This platform integrates social login options, recent chat history, and customizable interactions to deliver tailored responses, focusing on Tibetan culture, language, and education.
Figma file: [Route to Figma](https://www.figma.com/design/ZPPRfFT8H70pNjPqfIyEeJ/padma-chat?node-id=0-1&t=06KGc324s1Ox1uez-1)
### Completion Criteria
1. Signin and Signout Page should be available
2.  Main Homepage design should be ready and Prototyped.
3. dark mode implementation should be there
4. share button should open a pop up to copy link
5.  left sidebar should contain recent history
6.  the overall design should align with Monlam Theme and should give a cultural glimpse through vector svgs or logo

### Implementation Plan
1. Initializing  the utilities like colour usage, text and collect logos and images to be use.
2. create the main home page design as per mentioned. 
3. breaking repeated design to components.
4. signup and signin page
5. prototyping the design

### SubTasks

- [x] Collecting Design utils
- [x]  Creating Home Page (Sidebar)
- [x]  Signin and Signup Page
- [x]  Creating Home Page (center only)
- [x] Dark mode and Light Mode
- [x]  Prototyping and micro interaction
- [x] Tibetan Translation ( Process)
- [x] mobile mock

**Comment by kaldan007** [comment]
https://huggingface.co/chat/ @TenzDelek check out for inspiration

**Comment by TenzDelek** [comment]
as per the discussion (7th Oct, 2024) these changes have been reflected successfully: 
## Web
- [x] Four card in the homepage and similar with for the input field as per the card
- [x]  increasing the sidebar logo and adjusting the place as per the grid
- [x] moving Auth to the bottom left sidebar 
- [x]  Adjusting the user profile to the bottom sidebar
## Mobile
- [x] Shifting the text bubble position to remove whitespace
- [x]  Changing the hamburger menu to a better one 
- [x] editing the edit popup 
cc @kaldan007
