### ISSUE TITLE
Logo Design for Monlam Translate and Monlam Chatbot

### ISSUE THREAD

**Issue by TenzDelek** [OpenPecha/monlamai-feedbucket#165]
### Description
To create Logo for Monlam Translate and Monlam Chatbot

### Completion Criteria

1. design align with the current branding
2. understanding the boarder overview for the logo
3. Two Svg/png image logo### Implementation Plan
1. Create a rough design on paper to verify with the Maintainer
2. implement the design on either illustrator or figma

### SubTasks

- [x] Documenting the Logo Brief
- [x] Creating Logo idea on paper
- [x] implement the design on figma ( Monlam Translate)
- [x] implement the design on figma ( Monlam Chatbot)

**Comment by TenzDelek** [comment]
figma link : https://www.figma.com/design/ZPPRfFT8H70pNjPqfIyEeJ/padma-chat?node-id=426-12&t=pTocoJ6CXlqi32Bh-1

**Comment by Tendolls** [comment]
Please refer to the changes discussed. chatbot will be called Monlam AI and MT logo's background shouldn't be black. @TenzDelek
