### ISSUE TITLE
CR030:Implement Visual and Audio Feedback for Microphone Activation

### ISSUE THREAD

**Issue by Tendolls** [OpenPecha/monlamai-feedbucket#168]
**Description:**
Enhance the one-tap microphone access in the Monlam Translate app with visual and audio feedback to notify users when the microphone is active. This will ensure users are aware of the recording status, making the experience more intuitive.

https://github.com/user-attachments/assets/c40e7ebc-b67a-4cc9-9a98-d4ddaea13989

## Sub-tasks

- [x] one tap microphone access
- [x] update recording UI with animation
- [x] sound effect on mic activation 
- [x] Add on test flight for IOS and internal test android

## Reviewer

- [x] @Tendolls 
- [ ] @kaldan007

**Comment by tentamdin** [comment]
@Tendolls so I will try to make the UI the same as google translate. Cause we don't have any UI for this and specific audio feedback too.

**Comment by Tendolls** [comment]
@tentamdin https://www.figma.com/design/V6LW1I1QvSdqXnlsRsJiuK/Monlam-Mobile-Application-Mockup?node-id=1640-7728&t=bMzjh1Y9S6x3FynA-1

**Comment by tentamdin** [comment]
@Tendolls is the one-tap mic access for all screens with audio recoding, like conversation, split and the transcribing screen

**Comment by Tendolls** [comment]
@tentamdin YES !

**Comment by Tendolls** [comment]
@tentamdin @kaldan007  for the audio sound we can play with the Tibetan Instrument.
 https://github.com/user-attachments/assets/e895aa23-8fdd-4984-9050-10529c783060
https://github.com/user-attachments/assets/83d51d20-a338-4625-967a-efabbe7a9377
