### ISSUE TITLE
Convert the PHP page to React Page for Monlam DIctionary

### ISSUE THREAD

**Issue by tenkus47** [OpenPecha/monlamai-feedbucket#172]
### Description

For the dictionary API, develop a UI with React to use the api and deploy on render for ease development

### Implementation plan

replicate a UI of dictionary in react  from the PHP hosted on monlamdictionary.com and then connect with monlam dictionary api and host it on monlam dictionay web.

### Subtask

**Frontend**
- [x] make a React app with routes
- [x] import font , style and assets
- [ ] replicate page for contact and info
- [ ] make homepage and connect to api
- [ ] deploy on render

## Card Reviewed by
- [ ] @tentamdin
