### ISSUE TITLE
CR039:Pop up logic on the Nyamrub Mobile and Desktop

### ISSUE THREAD

**Issue by kaldan007** [OpenPecha/monlamai-feedbucket#182]
**Description**
Pop up message is required to emphasise the user to sign in to access the leaderboard reminder rather than to exit to the home page as it may lead to frustration to go to the contribute section again and again.

- pop up is required after the completion, where we show the leaderboard link to check the rank for the participants who haven't signed in. as it directly leads to the home page. 
![Image](https://github.com/user-attachments/assets/e0d96f3f-3505-4d5d-8e4b-02c4136bfc98)

**Pop up message** 
⚠️ Access Denied to Leaderboard
It looks like you're not signed in, so you can’t track your contributions on our leaderboard just yet.

**Sign in now to:** [social sign in options to be shown]
Monitor your contributions in real-time.
Get included in the yearly "Top Contributor Award"
Don't worry, though—all your contributions are safe with us.

**Comment by Tendolls** [comment]
**Bugs after beta testing** ; The level and percentage of the contribution needs to be accurate and how does it calculate? @kaldan007 @Karma-Tsering

**Comment by Karma-Tsering** [comment]
As of now we are not calculating level and percentage. The data show in ui is static.

cc: @Tendolls

**Comment by Karma-Tsering** [comment]
### Subtasks

- [x] Create popup modal
- [x] Check for authorized and anonymous user
- [x] Link popup for each contribution and validation

### Reviewer
- [x] @tenkus47

**Comment by Tendolls** [comment]
@Karma-Tsering The whole idea of pop up message is missing!! please include
 **Pop up message**
⚠️ Access Denied to Leaderboard
It looks like you're not signed in, so you can’t track your contributions on our leaderboard just yet.

Sign in now to: [social sign in options to be shown]
Monitor your contributions in real-time.
Get included in the yearly **"Top Contributor Award"**
Don't worry, though—all your contributions are safe with us.

**Comment by Karma-Tsering** [comment]
# User Sign-In Update

The current pop-up message appears too lengthy and difficult to read for users. To enhance clarity and readability, we've decided to update it based on discussions with **Tendol**.

## Updated Message

> **"It looks like you're not signed in. Please log in now to track your contributions and compete to win the Best Contributor Award."**


## Subtasks

- [x] Update pop up message
- [x] Remove progress section from leaderboard
